//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSS.Acupressure.App
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("TSS.Acupressure.App.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            script = -22589,
            style = -5605,
            index = -2501,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            KFOmCnqEu92Fr1Mu4mxK = -14762,
            KFOmCnqEu92Fr1Mu72xKOzY = -13425,
            KFOmCnqEu92Fr1Mu4WxKOzY = 7437,
            KFOmCnqEu92Fr1Mu7GxKOzY = 13338,
            KFOmCnqEu92Fr1Mu5mxKOzY = 20676,
            KFOmCnqEu92Fr1Mu7mxKOzY = 22659,
            KFOmCnqEu92Fr1Mu7WxKOzY = 27179,
        }
    }
}
