<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.42.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cod.IoT.Core.Standard\Cod.IoT.Core.Standard.csproj" />
    <ProjectReference Include="..\Cod.IoT.Networking\Cod.IoT.Networking.csproj" />
  </ItemGroup>

</Project>
