<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Cod.IoT</RootNamespace>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <NoWarn>1701;1702;SA0001</NoWarn>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' == '' ">1.0.0.0-prerelease</Version>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' != '' ">$(BUILD_BUILDNUMBER)</Version>
  </PropertyGroup>

  <Import Project="..\Cod.IoT\Cod.IoT.Abstrations\Cod.IoT.Abstrations.projitems" Label="Shared" />
  <Import Project="..\Cod.IoT\Cod.IoT.Core\Cod.IoT.Core.projitems" Label="Shared" />
  <Import Project="..\Cod.IoT\Cod.IoT.Core.Extendable\Cod.IoT.Core.Extendable.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Hashing" Version="8.0.0" />
  </ItemGroup>

</Project>
